---
title: '2018-12-12'
author: "林茂廷"
date: "12/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$書籍館藏地 %>%
  as.factor %>%
  levels -> storageLocations
```

```{r}
libraryData$書籍館藏地 <-
  as.factor(libraryData$書籍館藏地)
levels(libraryData$書籍館藏地) -> storageLocations
```

```{r}
i<-2
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
```

```{r}
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}

```


```{r}
names(allBorrowCount) <- storageLocations
```

## 不同學院借書量

```{r}
libraryData$學院 %>% as.factor %>% levels -> college

#0 
collegeBorrowCount <- vector("numeric",length(college))
for(i in c(1:length(college))){
#1
college_i <- college[i]
#2
numericalIndexForSubsample<-which(libraryData$學院 == college_i)
collegesubsample_i <- libraryData[numericalIndexForSubsample,]
#3
collegeBorrowCount_i <- nrow(collegesubsample_i)
#4
collegeBorrowCount[[i]]<-collegeBorrowCount_i 

}

```


### 每位學生借書量

```{r}

libraryData$學號 %>% as.factor %>% levels -> student
libraryData$學號 %>% unique -> student
#0
studentBorrow <- vector("numeric", length(student))
for(i in c(1:length(student))){
# 1
student_i <- student[i]
# 2
numericalIndex <- which(libraryData$學號 == student_i)
studentSubsample_i <- libraryData[numericalIndex,]
# 3
studentBorrow_i <- nrow(studentSubsample_i)
# 4
studentBorrow[[i]] <- studentBorrow_i
}
```



###

$$\sum_{i=1}^{10} i$$

```{r}
ans<-0
for(i in 1:10){
  newlyAdded<-i
  ans<-ans+newlyAdded
}

```

