---
title: '2018-12-05'
author: "林茂廷"
date: "12/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)

```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData %>%
  mutate_at(
    vars(學院,書籍館藏地,書籍類別),
    funs(
     as.factor(.)
    )
  ) -> libraryData

libraryData %>%
  mutate(
    借閱時間=ymd_hms(借閱時間,tz="Asia/Taipei")
  ) -> libraryData


```

```{r}
## 1
max(libraryData$讀者借閱冊數)-> maxNumber
min(libraryData$讀者借閱冊數)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
```


```{r}
## 1
max(libraryData$讀者借閱冊數)-> maxNumber
min(libraryData$讀者借閱冊數)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)

## 2
max(libraryData$入學年)-> maxNumber
min(libraryData$入學年)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)

## 3
max(libraryData$書籍上架年月)-> maxNumber
min(libraryData$書籍上架年月)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
```

minMaxFun(x)
```{r}
minMaxFun <- function(x){
max(x)-> maxNumber
min(x)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)}
```

```{r}
minMaxFun(libraryData$讀者借閱冊數)-> a1
a1
minMaxFun(libraryData$入學年)->a2
a2
minMaxFun(libraryData$書籍上架年月)->a3
a3
```


```{r}
minMaxFun2 <- function(x){
max(x)-> maxNumber
min(x)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)-> result
return(result)
}
```


```{r}
minMaxFun3 <- function(x){
max(x)-> maxNumber
min(x)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
return(maxNumber)
}
```


```{r}
minMaxFun3(libraryData$讀者借閱冊數)-> a1
a1
minMaxFun3(libraryData$入學年)->a2
a2
minMaxFun3(libraryData$書籍上架年月)->a3
a3
```


```{r}
minMaxFun4 <- function(x){
max(x)-> maxNumber
min(x)-> minNumber
print(
  paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
  ) 
return(maxNumber)
}
```

```{r}
minMaxFun4(libraryData$讀者借閱冊數)-> a1
a1
```

###  練習

```{r}
!is.numeric(libraryData$學號)

!is.numeric(libraryData$書籍類別)

```

```{r}

not_numeric<- function(x){
  !is.numeric(x)
}
```

```{r}
not_numeric<- function(x){
  !is.numeric(x) -> result
  return(result)
}
```



```{r}
not_numeric(libraryData$學號)
```
TRUE

### 練習：
找出屬於"人文學院"的子樣本。

```{r}
(libraryData$學院=="人文學院")-> logIndex
libraryData[logIndex,]-> subsample
```

找出屬於"社會科學院"的子樣本。

```{r}
(libraryData$學院=="社會科學院")-> logIndex
libraryData[logIndex,]-> subsample
```

```{r}
findMyCollege<-function(x){
  (libraryData$學院==x)-> logIndex
libraryData[logIndex,]-> subsample
return(subsample)
}
```

## Grouping and summarise group feature
```{r}
## grouping
findMyCollege("人文學院")-> sample1
## group feature summary
nrow(sample1)


findMyCollege("社會科學院") -> sample2
nrow(sample2)
```

```{r}
libraryData %>%
  group_by(學院) %>%
  summarise(
    學院借閱冊數=length(學號)
  )
  
```

```{r}
libraryData %>%
  select(讀者借閱冊數,書籍出版日期) %>%
  summarise(
    讀者平均借閱冊數=mean(讀者借閱冊數),
    最小書籍出版日期=min(書籍出版日期),
    最大書籍出版日期=max(書籍出版日期)
  )
```

